name: Linting
on:
  pull_request:
    branches: [main]
jobs:
  build:
    name: Lint stuff
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Lint
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JAVA_FILE_NAME: style.xml
        VALIDATE_JAVA: true